"""empty message

Revision ID: 0ecc3715c09c
Revises: f6845bf9efbd
Create Date: 2023-09-19 11:02:30.229075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ecc3715c09c'
down_revision = 'f6845bf9efbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('problem_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('prices_problem_id_fkey', 'prices', 'service_params', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prices_problem_id_fkey', 'prices', type_='foreignkey')
    op.drop_column('prices', 'problem_id')
    # ### end Alembic commands ###
