"""empty message

Revision ID: 59059b09650c
Revises: 0ecc3715c09c
Create Date: 2023-10-17 14:34:40.526952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59059b09650c'
down_revision = '0ecc3715c09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('model_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ordered_damages', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ordered_problems', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('orders_ordered_service_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key('orders_model_id_fkey', 'orders', 'service_params', ['model_id'], ['id'])
    op.drop_column('orders', 'ordered_service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordered_service_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('orders_model_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ordered_service_id_fkey', 'orders', 'prices', ['ordered_service_id'], ['id'])
    op.drop_column('orders', 'ordered_problems')
    op.drop_column('orders', 'ordered_damages')
    op.drop_column('orders', 'model_id')
    # ### end Alembic commands ###
