"""empty message

Revision ID: f6845bf9efbd
Revises: 12a6d702995f
Create Date: 2023-09-14 11:43:10.362457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6845bf9efbd'
down_revision = '12a6d702995f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referal_codes',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('service_type_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('referrer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('referrer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invite_by_sms', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(now())::timestamp(0) without time zone'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_params.id'], name='referal_codes_service_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='referal_codes_pkey')
    )
    op.create_table('user_service_states',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('service_type_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_params.id'], name='user_service_states_service_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_service_states_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_service_states_pkey')
    )
    op.create_table('user_text_store',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('utm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(now())::timestamp(0) without time zone'), autoincrement=False, nullable=True),
    sa.Column('custom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_text_store_pkey')
    )
    op.create_index('ix_user_text_store_phone', 'user_text_store', ['phone'], unique=False)
    op.add_column('files', sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('files_created_by_fkey', 'files', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('avatar_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_avatar_id_fkey', 'users', 'files', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_avatar_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.drop_constraint('files_created_by_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'created_by')
    op.drop_index('ix_user_text_store_phone', table_name='user_text_store')
    op.drop_table('user_text_store')
    op.drop_table('user_service_states')
    op.drop_table('referal_codes')
    # ### end Alembic commands ###
